# Generated by Django 4.1.7 on 2023-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced', models.FloatField()),
                ('consumed', models.FloatField()),
                ('hash', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('txId', models.CharField(blank=True, default=None, max_length=66, null=True)),
            ],
        ),
    ]
