# Generated by Django 4.1.7 on 2023-02-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy',
            old_name='consumed',
            new_name='consumed_energy_in_watt',
        ),
        migrations.RenameField(
            model_name='energy',
            old_name='produced',
            new_name='produced_energy_in_watt',
        ),
    ]
