# Generated by Django 4.1.7 on 2023-02-16 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_consumed_energy_consumed_energy_in_watt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
