# Generated by Django 4.1.7 on 2023-02-17 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_energy_datetime2'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
