# Generated by Django 4.1.7 on 2023-02-17 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_energy_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
