# Generated by Django 4.1.7 on 2023-02-17 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_energy_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter the publication date in YYYY-MM-DD format.', verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Publication time'),
        ),
    ]
