# Generated by Django 4.1.7 on 2023-02-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_energy_date_alter_energy_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Enter the publication date in YYYY-MM-DD format.', verbose_name='Publication date'),
        ),
    ]
