# Generated by Django 4.1.7 on 2023-02-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_energy_consumed_energy_in_watt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='energy',
            name='consumed_energy_in_watt',
            field=models.FloatField(verbose_name='Enegia Consumata'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='energy',
            name='produced_energy_in_watt',
            field=models.FloatField(verbose_name='Enegia Prodotta'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66, null=True, verbose_name='Id Transazione'),
        ),
    ]
