# Generated by Django 4.1.7 on 2023-03-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_energy_datetime_alter_energy_date_alter_energy_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='energy',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='energy',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
