# Generated by Django 4.1.7 on 2023-03-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_energy_datetime_alter_energy_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='energy',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True, verbose_name='Id Transazione'),
        ),
    ]
